### PR TITLE
Layer 139 support

### PR DESCRIPTION
**Pull request by cyberash-dev**
These are commits with layer 139 support. This allows to get RTMP settings of live stream.

### CODE REVIEW

**Comment by painor** [comment]
could you please do `prettier --write .` on it

**Comment by cyberash-dev** [comment]
> could you please do `prettier --write .` on it

I do it.

**Comment by painor** [comment]
oh wow it made it worse lol

**Comment by cyberash-dev** [comment]
> oh wow it made it worse lol

Why do it made worse? Maybe i have wrong prettier version or do it from wrong directory?

**Comment by painor** [comment]
I'll fix it don't worry, prettier is using the wrong line ending for you (you probably are using Linux?)

**Comment by painor** [comment]
Should be in master now.

**Comment by cyberash-dev** [comment]
> I'll fix it don't worry, prettier is using the wrong line ending for you (you probably are using Linux?)

Yes, I'm using Ubuntu Linux.
Thank you for fix.

**Comment by adhil72** [comment]
@cyberash-dev how to get it. what function i have to call to get

**Pull request closed without merging**
