### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jencansee**
Also, I think that it would be better to rename "Obtaining your app ID and hash" into "How to get started"  and rewrite that part as in documentation. Should I do it?

### CODE REVIEW

**Comment by painor** [comment]
can you also rename Running GramJS to Running GramJS on browsers ? since that part specifically refers to browsers

**Comment by painor** [comment]
if you want to rename it to how to get started we probably need to provide more info besides just obtaining the hash and id

**Comment by Jencansee** [comment]
Sure, I'll work on it.

**Comment by roj1512** [comment]
@Jencansee use ``` for multiline instead of `.

**Comment by Jencansee** [comment]
> @Jencansee use ``` for multiline instead of `.

What do you mean? All multilines are already inside ```

**Comment by roj1512** [comment]
I mean that you should do this:

```
Install GramJS:

\`\`\`bash
npm i telegram
\`\`\`
```

Instead of this:

```
Install GramJS:

\`npm i telegram\`
```

**Comment by painor** [comment]
looks good. I think maybe we should also mention that `StoreSession` also exists

```ts
const stringSession = new StringSession(""); // use this if you want to save the auth key to a string
const storeSession = new SoreSession("folder_name"); // use this if you want to save the auth key to a folder
```

**Comment by painor** [comment]
Looks good to me, if you don't have any more changes I can merge this.

**Comment by Jencansee** [comment]
Yep, everything's good.

**Pull request merged**
