### PR TITLE
Improve Webpack configuration

### PR DESCRIPTION
**Pull request by roj1512**
- Get `mode` from env or go with `development`.
- Set `output.library` to `telegram` to match with package name in npm.
- Remove `output.auxiliaryComment` as it is not required.
- Set `output.filename` to `telegram.js` for better readability.

### CODE REVIEW

**Comment by roj1512** [comment]
I think the filename can better be `telegram.js`, waiting for your opinions. :)

**Comment by painor** [comment]
> I think the filename can better be `telegram.js`, waiting for your opinions. :)

Yes. if you are going to rename it to telegram then telegram.js makes more sense

**Comment by roj1512** [comment]
Done, @painor!

**Comment by painor** [comment]
Would you be able to update the example file since it uses gramjs?

**Comment by roj1512** [comment]
Sure.

**Comment by roj1512** [comment]
Did that, too.

**Comment by painor** [comment]
what about this https://github.com/gram-js/gramjs/blob/master/examples/simpleLogin.js#L54

**Comment by roj1512** [comment]
Oops.

**Review by painor — APPROVED** [review]

**Pull request merged**
