### PR TITLE
Update to Layer 140

### PR DESCRIPTION
**Pull request by butthx**
- [x] Change the regex to fixed parsing TLSchema like : `can_delete_channel:flags2.0?true`
- [x] Running `prettier -w .`
- [x] fix conflicts

### CODE REVIEW

**Comment by butthx** [comment]
ofc, i am tested and it work fine.
markup_46110

**Comment by painor** [comment]
can you do something about the new lines ? 
```
git config --global core.autocrlf true
```

**Comment by butthx** [comment]
> can you do something about the new lines ?
> 
> ```
> git config --global core.autocrlf true
> ```

after do 
```bash 
git config --global core.autocrlf true
``` 
should be i am do prettier and push again? sorry i am new for that

**Comment by butthx** [comment]
> > can you do something about the new lines ?
> > ```
> > git config --global core.autocrlf true
> > ```
> 
> after do
> 
> ```shell
> git config --global core.autocrlf true
> ```
> 
> should be i am do prettier and push again? sorry i am new for that

nvm. i got this one https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Review by painor — APPROVED** [review]

**Pull request merged**
