### PR TITLE
WIP Updating event models

### PR DESCRIPTION
**Pull request by watzon**
This isn't ready to be merged yet, but I want to be able to push and get feedback on changes I'm making. So far in this PR I have:

- Replaced all instances of `console.log` with `this._log` in `TelegramClient` (definitely will need to be done other places too)
- Updated the logger, making it capable of receiving multiple arguments like `console.log` does.
- Added various filters to `NewMessage`, allowing all of the same functionality telethon's `NewMessage` has.

Ideally there are a couple more changes I'd like to make, but I'm not sure of the best way to go about making them. The first is that certain objects, especially `Message`, need to be wrapped and have their prototypes extended so that we can add methods to them that are specific to that object. For instance `Message` should have `respond`, `delete`, etc.

### CODE REVIEW

**Comment by painor** [comment]
you can have a TS definition of a patched Message object to add the respond/delete etc functions

**Comment by watzon** [comment]
So the swap can be reverted if that's the order you prefer it in, but I thought it made more sense to have the event first and then the callback, since generally callbacks go last. That way instead of this:

```javascript
client.addEventHandler((update) => {
    // ...
}, new NewMessage())
```

You can do

```javascript
client.addEventHandler(new NewMessage(), (update) => {
    // ...
})
```

Which I feel is more expected. Either way I think it would be nice to have a decorator eventually to abstract that away.

**Comment by painor** [comment]
@watzon wouldn't you need to specify the event type always this way ? . the event type can be ommited and be .Raw or .NewMessage by default if it was put second. also https://github.com/LonamiWebs/Telethon/blob/master/telethon/client/updates.py#L101

**Comment by watzon** [comment]
Hmm good point. I didn't know that having the event type be optional was a thought. I'll go ahead and swap them back around.

Currently the `tl/custom` directory is empty. Should I stick custom objects that extend builtins in there?

**Comment by painor** [comment]
@watzon yep.

**Comment by painor** [comment]
I'm going to merge this and maybe the custom message can be in its own PR

**Pull request merged**
