### PR TITLE
Fixed small bug

### PR DESCRIPTION
**Pull request by BLUE-DEVIL1134**
just fixed a small bug in parseUsername..
was causing regularly when called sendMessage..

### CODE REVIEW

**Comment by painor** [comment]
hey, thanks for the PR. it appears I looked at the wrong place. that code is fine but we're missing the ignore case flag from these regex expressions. 
USERNAME_RE
TG_JOIN_RE
VALID_USERNAME_RE

They should be at the top of the file so just add the 'i' flag to them 
`new Regex(expression,'i');`

**Comment by BLUE-DEVIL1134** [comment]
and should this lowercase one be removed or will keep it there

**Comment by painor** [comment]
> and should this lowercase one be removed or will keep it there

probably removed. the rest is good.

**Comment by BLUE-DEVIL1134** [comment]
Ok then.

**Pull request merged**
