### PR TITLE
useWSS default value

### PR DESCRIPTION
**Pull request by rojserbest**
Set the default value of useWSS to true if running from browser and potocol is https.

### CODE REVIEW

**Comment by rojserbest** [comment]
I get `Type 'boolean' is not assignable to type 'false'.`, what should I do to fix it?

**Comment by rojserbest** [comment]
I think it's fine because there are many other errors like that when building.

**Comment by BLUE-DEVIL1134** [comment]
> I get `Type 'boolean' is not assignable to type 'false'.`, what should I do to fix it?

This is because @painor made it `false | undefined` which should be `boolean | undefined`

**Comment by rojserbest** [comment]
> > I get `Type 'boolean' is not assignable to type 'false'.`, what should I do to fix it?
> 
> This is because @painor made it `false | undefined` which should be `boolean | undefined`

Where should I edit that?
And one question: Is `typeof window !== 'undefined'` better than `IS_NODE`? Cz I saw it somewhere

**Comment by BLUE-DEVIL1134** [comment]
> Set the default value of useWSS to true if running from browser and potocol is https.

No, its shouldn't be cause many places like, freenom and others provide `http://` and not `https://`..
So, the best that can be done is add this to docs.

**Comment by rojserbest** [comment]
> > Set the default value of useWSS to true if running from browser and potocol is https.
> 
> No, its shouldn't be cause many places like, freenom and others provide `http://` and not `https://`..
> So, the best that can be done is add this to docs.

Well, this doesn't make it true every time if running from browser, if you read it you will see `window.location.protocol == 'https:'`.

**Comment by BLUE-DEVIL1134** [comment]
> > > Set the default value of useWSS to true if running from browser and potocol is https.
> > 
> > 
> > No, its shouldn't be cause many places like, freenom and others provide `http://` and not `https://`..
> > So, the best that can be done is add this to docs.
> 
> Well, this doesn't make it true every time if running from browser, if you read it you will see `window.location.protocol == 'https:'`.

Then @painor , you can do this, if its https then auto set usewss true

**Comment by rojserbest** [comment]
Not now, he should first review it and tell us if `typeof window !== 'undefined'` is better than `IS_NODE`...

**Comment by painor** [comment]
you should add `boolean` to useWSS in `TelegramClientParams `. it's set to false now. 

it should also check if window exits when doing `window.location.protocol` so do both.

**Comment by rojserbest** [comment]
@painor done.

**Pull request merged**
